### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by warfollowsme** [btolfa/meta-tionpro28#1]
Здравствуйте. 
По завершению 

```
bitbake core-image-minimal
```

выпала ошибка

```
ERROR: No recipes available for:
/home/debug/fsl-community-bsp/sources/meta-tionpro28/recipes-support/boost/boost_1.56.0.bbappend
ERROR: Command execution failed: Exited with 1
```

**Comment by btolfa** [comment]
Если boost не нужен (а он скорее всего не нужен), просто удалите директорию meta-tionpro28/recipes-support/boost
Если нужен, переименуйте boost_1.56.0.bbappend до актуальной версии.
Ещё судя по всему, вы используете не самую свежую версию yocto, на текущий день это dizzy (1.7), а вы следуя инструкции с https://github.com/Freescale/fsl-community-bsp-platform установили и скачали daizy (1.6.2)
Рекомендую использовать свежую версию yocto, для этого следуя инструкции с https://github.com/Freescale/fsl-community-bsp-platform, только вместо 
$ repo init -u https://github.com/Freescale/fsl-community-bsp-platform -b daisy
нужно использовать
$ repo init -u https://github.com/Freescale/fsl-community-bsp-platform -b dizzy

**Comment by warfollowsme** [comment]
Спасибо. Разобрался, скомпилил. Все отлично. Образ рабочий. За сборку отдельное спасибо очень облегчила задачу. 
Есть доп. вопрос: как добавить свою лицензию? У меня есть задача попробовать на тионе .net. Нашел meta-mono для yocto. Но этот уровень добавляет к образу 340мб, учитывая что сам образ весит Ок. 90мб. Глянув зависимости и понял что там тянутся все графичиские зависимости типо gdi+. Попытался все это выкинуть создав свой image, но наткнулся на проблему с лицензией. Как ее добавить в свой image. В стандартном моно лицензия тянется из recipe-Sato. Но мне sato не нужен, нужно просто создать файл лицензии и указать его chksum. Но в мануалах не нашел информации как это сделать. Не подскажете? Или может хотя бы ссылку на описание знаете. Буду благодарен.

**Comment by btolfa** [comment]
Про создание (и редактирование) рецепта можно почитать тут http://www.yoctoproject.org/docs/1.7/dev-manual/dev-manual.html#new-recipe-writing-a-new-recipe
Про лицензии http://www.yoctoproject.org/docs/1.7/dev-manual/dev-manual.html#new-recipe-licensing
Вкратце нужно указать  путь на файл с лицензией и какой-нибудь md5. Запустить сборку bitbake <имя пакета>, среда сборки выдаст ошибку о не соответствии контрольной суммы и предложит правильную.
Если честно не понимаю как другая лицензия может помочь избавиться от зависимостей.
